global using BasicGameFrameworkLibrary.BasicGameDataClasses;
global using BasicGameFrameworkLibrary.CommonInterfaces;
global using BasicGamingUIBlazorLibrary.Bootstrappers;
global using PaydayCP.ViewModels;
global using BasicGameFrameworkLibrary.DIContainers;
global using BasicGameFrameworkLibrary.TestUtilities;
global using BasicGamingUIBlazorLibrary.Shells;
global using Microsoft.AspNetCore.Components;
global using BasicGameFrameworkLibrary.MultiplayerClasses.LoadingClasses;
global using BasicGameFrameworkLibrary.ViewModels;
global using PaydayCP.Data;
global using BasicGameFrameworkLibrary.MiscProcesses;
global using BasicGamingUIBlazorLibrary.BasicControls.SimpleControls;
global using BasicGamingUIBlazorLibrary.Extensions;
global using CommonBasicLibraries.CollectionClasses;
global using BasicGameFrameworkLibrary.MultiplayerClasses.BasicGameClasses;
global using BasicGameFrameworkLibrary.MultiplayerClasses.MiscHelpers;
global using BasicGameFrameworkLibrary.CommandClasses;
global using BasicGameFrameworkLibrary.Dice;
global using BasicGameFrameworkLibrary.MultiplayerClasses.InterfaceModels;
global using BasicGameFrameworkLibrary.ScoreBoardClassesCP;
global using PaydayCP.Graphics;
global using PaydayCP.Cards;
global using SvgHelper.Blazor.Logic;
global using SvgHelper.Blazor.Logic.Classes.SubClasses;
global using System.Drawing;
global using SKColors = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using aa = BasicGameFrameworkLibrary.DIContainers.Helpers;
global using bb = BasicBlazorLibrary.Components.CssGrids.Helpers;
