global using GamePackageSerializeGenerator;
global using SpellingLibrary.Core;
global using js = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.SystemTextJsonStrings;
global using CommonBasicLibraries.CollectionClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;