global using BasicGameFrameworkLibrary.BasicGameDataClasses;
global using BasicGameFrameworkLibrary.CommonInterfaces;
global using BasicGamingUIBlazorLibrary.Bootstrappers;
global using TicTacToeCP.ViewModels;
global using BasicGameFrameworkLibrary.DIContainers;
global using BasicGameFrameworkLibrary.TestUtilities;
global using BasicGamingUIBlazorLibrary.Shells;
global using Microsoft.AspNetCore.Components;
global using BasicGameFrameworkLibrary.MultiplayerClasses.LoadingClasses;
global using BasicGameFrameworkLibrary.ViewModels;
global using TicTacToeCP.Data;
global using BasicGameFrameworkLibrary.MiscProcesses;
global using BasicGamingUIBlazorLibrary.BasicControls.SimpleControls;
global using BasicGamingUIBlazorLibrary.Extensions;
global using CommonBasicLibraries.CollectionClasses;
global using BasicGamingUIBlazorLibrary.BasicControls.GameBoards;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using Microsoft.AspNetCore.Components.Rendering;
global using SvgHelper.Blazor.Logic;
global using SvgHelper.Blazor.Logic.Classes.Interfaces;
global using SvgHelper.Blazor.Logic.Classes.SubClasses;
global using System.Drawing;
global using cc = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using aa = BasicGameFrameworkLibrary.DIContainers.Helpers;
