global using BasicGameFrameworkLibrary.BasicGameDataClasses;
global using BasicGameFrameworkLibrary.CommonInterfaces;
global using BasicGamingUIBlazorLibrary.Bootstrappers;
global using MinesweeperCP.ViewModels;
global using BasicGameFrameworkLibrary.DIContainers;
global using BasicGamingUIBlazorLibrary.GameGraphics.Base;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Rendering;
global using MinesweeperCP.Data;
global using SvgHelper.Blazor.Logic;
global using SvgHelper.Blazor.Logic.Classes.Interfaces;
global using SvgHelper.Blazor.Logic.Classes.SubClasses;
global using cc = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using CommonBasicLibraries.CollectionClasses;
global using MinesweeperCP.Logic;
global using System;
global using System.Linq;
global using aa = BasicGameFrameworkLibrary.DIContainers.Helpers;
global using BasicGamingUIBlazorLibrary.BasicControls.SimpleControls;
global using BasicGamingUIBlazorLibrary.Extensions;
