global using CommonBasicLibraries.CollectionClasses;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.RandomGenerator;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
