global using BasicGameFrameworkLibrary.BasicGameDataClasses;
global using BasicGameFrameworkLibrary.CommonInterfaces;
global using BasicGamingUIBlazorLibrary.Bootstrappers;
global using YahtzeeHandsDownCP.ViewModels;
global using BasicGameFrameworkLibrary.DIContainers;
global using BasicGameFrameworkLibrary.TestUtilities;
global using BasicGamingUIBlazorLibrary.Shells;
global using Microsoft.AspNetCore.Components;
global using BasicGameFrameworkLibrary.MultiplayerClasses.LoadingClasses;
global using BasicGameFrameworkLibrary.ViewModels;
global using YahtzeeHandsDownCP.Data;
global using BasicGameFrameworkLibrary.MiscProcesses;
global using BasicGamingUIBlazorLibrary.BasicControls.SimpleControls;
global using BasicGamingUIBlazorLibrary.Extensions;
global using CommonBasicLibraries.CollectionClasses;
global using BasicGameFrameworkLibrary.MultiplayerClasses.BasicGameClasses;
global using BasicGameFrameworkLibrary.MultiplayerClasses.MiscHelpers;
global using BasicGameFrameworkLibrary.CommandClasses;
global using BasicGameFrameworkLibrary.Dice;
global using BasicGameFrameworkLibrary.MultiplayerClasses.InterfaceModels;
global using BasicGameFrameworkLibrary.ScoreBoardClassesCP;
global using aa = BasicGameFrameworkLibrary.DIContainers.Helpers;
global using BasicGamingUIBlazorLibrary.GameGraphics.Base;
global using YahtzeeHandsDownCP.Cards;
global using System.Drawing;
global using BasicGameFrameworkLibrary.DrawableListsObservable;
global using BasicGamingUIBlazorLibrary.BasicControls.SpecializedFrames.Hands;
global using BasicGameFrameworkLibrary.BasicDrawables.Interfaces;
global using BasicGamingUIBlazorLibrary.GameGraphics.Cards;
global using BasicGamingUIBlazorLibrary.GameGraphics.MiscClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using cc = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using SvgHelper.Blazor.Logic;
global using SvgHelper.Blazor.Logic.Classes.Interfaces;
global using SvgHelper.Blazor.Logic.Classes.SubClasses;
global using bb = BasicBlazorLibrary.Components.CssGrids.Helpers;
