global using BasicGameFrameworkLibrary.BasicEventModels;
global using BasicGameFrameworkLibrary.BasicGameDataClasses;
global using BasicGameFrameworkLibrary.CommandClasses;
global using BasicGameFrameworkLibrary.CommonInterfaces;
global using BasicGameFrameworkLibrary.DIContainers;
global using BasicGameFrameworkLibrary.MiscProcesses;
global using BasicGameFrameworkLibrary.TestUtilities;
global using BasicGameFrameworkLibrary.ViewModelInterfaces;
global using BasicGameFrameworkLibrary.ViewModels;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using CommonBasicLibraries.BasicUIProcesses;
global using MessengingHelpers;
global using MVVMFramework.ViewModels;
global using aa = BasicGameFrameworkLibrary.DIContainers.Helpers;
global using BasicBlazorLibrary.Components.BaseClasses;
global using Microsoft.AspNetCore.Components;
global using CommonBasicLibraries.CollectionClasses;
global using Microsoft.JSInterop;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using cc = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using Microsoft.AspNetCore.Components.Rendering;
global using SvgHelper.Blazor.Logic;
global using SvgHelper.Blazor.Logic.Classes.Interfaces;
global using SvgHelper.Blazor.Logic.Classes.SubClasses;
global using System.Drawing;
global using BasicGameFrameworkLibrary.GameBoardCollections;
