global using BasicGameFrameworkLibrary.CommonInterfaces;
global using BasicGamingUIBlazorLibrary.Bootstrappers;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using GameLoaderBlazorLibrary;