global using BasicBlazorLibrary.Helpers;
global using WPFStartupLibrary;
global using Microsoft.Extensions.DependencyInjection;
global using AllMultiplayerGames.Blazor;
global using System.Windows;
global using BasicGamingUIBlazorLibrary.Extensions;
global using BasicGamingUIBlazorLibrary.Helpers;
global using GameLoaderBlazorLibrary;
global using ss = MultiplayerGamesBlazorLoaderLibrary.MainStartUp;
global using MultiplayerGamesBlazorLoaderLibrary;
