global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.AspNetCore.Components.Web;
global using BasicBlazorLibrary.Helpers;
global using MultiplayerGamesBlazorLoaderLibrary;
global using AllMultiplayerGames.Blazor;
global using GameLoaderBlazorLibrary;
global using BasicGamingUIBlazorLibrary.Helpers;
global using BasicGamingUIBlazorLibrary.Extensions;
global using bb = CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using ss = MultiplayerGamesBlazorLoaderLibrary.MainStartUp;